name: Upstream Sync

on:
  schedule:
    - cron: "0 * * * *"    # 每小时执行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Upstream Sync
        run: |
          git remote add upstream https://github.com/LobeHub/lobe-chat.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
